### ISSUE TITLE
Not cute enough.

### ISSUE THREAD

**Issue by this-vidor** [edwardandlena/edwardandlena.github.io#1]
Needs cuter.

**Comment by this-vidor** [comment]
Consider :sparkles: sparkles.

**Comment by esrice** [comment]
See 9ce1780f655357470c1a70bd23ece3d7dd112644 for progress on this issue

**Comment by this-vidor** [comment]
:giraffe:  :rainbow: Magnifique! :unicorn: :revolving_hearts:
