### ISSUE TITLE
api_key committed to public repository

### ISSUE THREAD

**Issue by this-vidor** [edwardandlena/edwardandlena.github.io#2]
I tried to hack your account using this. It looks like the api_key you added has very limited permissions associated with it. That said, this repository is public, and there are plenty of bots crawling GitHub searching for the keyword "api_key" in public repositories. So you should proceed on the assumption that that key is public knowledge.

**Comment by esrice** [comment]
Yes, it's a read-only key, and there's no way that I can find to not expose an API key on a front-end-only website hosting service like github pages.

...okay, I'll build a flask backend.

**Comment by this-vidor** [comment]
Don't give yourself the headache of maintaining a back-end for a static site!

It looks like ["Github Actions"](https://help.github.com/en/actions/configuring-and-managing-workflows/using-variables-and-secrets-in-a-workflow) is the term for the deployment hook, and you can configure secrets to be templated in at such a time. That said, your secrets will still be visible in the Javascript that gets loaded with the page, so this doesn't actually solve the issue.

If the token is just "public access", it is not unreasonable to make it accessible to the public. But if the token just gives "public access", why do you need a token at all? Shouldn't things that flickr makes available to the public... just be public, and not token-authorized?

**Comment by esrice** [comment]
Yes, I figured there are ways to not have it in the code but it still has to be exposed at some point on a frontend-only site.

They use the token to limit calls from a single user to 3600/hr. If someone steals my key and starts using it to look at public photos on flickr at a high rate and my key stops working, I'll worry about that in the unlikely event it actually happens.

Flask is fun, though, and I could use it to collect RSVPs in an sqlitedb.

**Comment by this-vidor** [comment]
What is not fun is wedding guests not being able to look up directions/timeline details on your wedding day because of a bug in your Flask server. Seriously. Build a Flask app for some other hobby project; for this, stick with the static approach, let GitHub or AWS worry about uptime.

Using a Flask server won't solve this problem for you in any kind of non-trivial way, either. You could have the front-end make dedicated API calls to fetch photos from your little Flask server, which then has to proxy them to Flickr, but it sounds like Flickr has given you a way to securely limit access control on that API key to what is already public, anyway, so I wouldn't worry about it.

Although I was able to scrape details about the Flickr account like Lena's full name, the date of her first upload, etc. Profile stuff.

**Comment by this-vidor** [comment]
One thing that would be safer would be to create a separate account that is the "Wedding Account" and use an API key from that account, instead of Lena's personal key. Also, why is this repo public? GitHub has unlimited private repos now.

**Comment by this-vidor** [comment]
So my suggestion is, in summary:

1.  Use static hosting for this project if at all possible.
2.  Rotate Lena's API key in case the permissions associated with that key ever change; it is now The Public's key.
3.  Create a dedicated account with a dedicated key that can be used for accessing Flickr photos.
4.  Make this repo private!

**Comment by esrice** [comment]
1. already am
2. A new key would be no different from an old key as a new one would still have to be exposed to use it in front-end, and anyway, it's a public key, not associated with her account, and guaranteed not to allow private access to anything by itself without an OAuth token.
3. The account _is_ a dedicated account; it just had to be associated with a name/email and I already have an account.
4. Github pages only works with public repositories. And if its contents are going to be publicly available as a website, I don't see how hiding them on github would make a difference anyway.

**Comment by this-vidor** [comment]
Re  4: The difference is the visibility of these issue threads, and the ability to traverse the entire `git` commit history.
